version: '3.8'
services:
  frontend:
    build: .
    environment:
      - VITE_BASE_URL=https://makna.be.vncnttan.my.id
      - VITE_ACCESS_TOKEN_KEY="token"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.makna-frontend.rule=Host(`makna.vncnttan.my.id`)"
      - "traefik.http.routers.makna-frontend.entrypoints=websecure"
      - "traefik.http.routers.makna-frontend.tls.certresolver=app1"
      - "traefik.http.services.makna-frontend.loadbalancer.server.port=80"
    restart: unless-stopped
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    external: true
    # Use existing traefik network

