version: '3.8'
services:
  frontend:
    build: .
    environment:
      - VITE_BASE_URL=https://makna.be.vncnttan.my.id
      - VITE_ACCESS_TOKEN_KEY="token"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webrtc-app.rule=Host(`makna.vncnttan.my.id`)"
      - "traefik.http.routers.webrtc-app.entrypoints=websecure"
      - "traefik.http.routers.webrtc-app.tls.certresolver=app1"
      - "traefik.http.services.webrtc-app.loadbalancer.server.port=39876"
    restart: unless-stopped
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    external: true  # Use existing traefik network

