name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  deploy-on-push-main:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Private Docker Registry
        uses: docker/login-action@v2
        with:
          registry: localhost:5000

      - name: Build Docker image and give it tag
        run: |
          docker build -t makna-frontend:latest .
          docker tag makna-frontend:latest localhost:5000/makna-frontend:latest

      - name: Push Docker image to local registry
        run: |
          docker push localhost:5000/makna-frontend:latest

      - name: Log in to Docker registry on runner
        run: |
          docker login localhost:5000

      - name: Pull Docker image on runner
        run: |
          docker pull localhost:5000/handy-backend:latest

      - name: Run Docker Compose
        run: |
          docker-compose down
          docker-compose up -d
